title: ðŸ‘ï¸ Eyeâ€¢Set Project
author: Marek Smigielski
email: marek.smigielski@gmail.com
description: >- 
  Eyeâ€¢Set is a mesh-connected camera trap system built for wildlife photographers and field researchers.
remote_theme: jekyll/minima@0b7ca6b


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  nav_pages:
    - about.md

  social_links:
    - title: Eyeâ€¢Set project at GitHub
      icon: github
      url: "https://github.com/eye-set"

  hide_site_feed_link: true
